Added new method/refactored others
crashteamdev/payment-proto pull request #4
Opened 2022-05-05 16:01 UTC by SageFreke

2022-05-05 16:03 UTC, vitaxa requested changes

2022-05-05 16:03 UTC, vitaxa commented on src/main/proto/payment.proto
> +  bool refundable = 7;
а это что значит?

2022-05-05 16:03 UTC, vitaxa commented on src/main/proto/payment.proto
> +message  Confirmation {
Тут пробел лишний

2022-05-06 07:15 UTC, SageFreke commented on src/main/proto/payment.proto
> +  bool refundable = 7;
прост номера пофиксил, там без изменений

2022-05-06 13:06 UTC, vitaxa requested changes

2022-05-06 13:06 UTC, vitaxa commented on src/main/proto/payment.proto
> +  string status = 3;
Надо переделать везде статусы на enum

2022-05-06 13:06 UTC, vitaxa commented on src/main/proto/payment.proto
> +  CancellationDetails cancellation_details = 6;
Можно выпилить и оставить только типа
`string details = 6`

2022-05-06 13:30 UTC, SageFreke commented on src/main/proto/payment.proto
> +  string payment_id = 1;
payment_id точна

2022-05-06 13:40 UTC, vitaxa approved these changes

2022-05-06 13:40 UTC, merged